export type RegistrationCopy = { en: string; mr: string; hi: string };
export type RegistrationEntry = {
  id: string;
  group: 'entity' | 'general' | 'sector';
  name: RegistrationCopy;
  summary: RegistrationCopy;
  documents: RegistrationCopy[];
  authority: string;
  complexity: number;
  tags: string[];
  officialUrl: string;
};

const copy = (en: string, mr: string, hi: string): RegistrationCopy => ({ en, mr, hi });

export const registrationCatalog: RegistrationEntry[] = [
  { id: 'proprietorship', group: 'entity', name: copy('Sole proprietorship', 'एकल मालकी व्यवसाय', 'एकल स्वामित्व व्यवसाय'), summary: copy('An individual-owned business; there is no separate central incorporation certificate. Local and tax registrations depend on activity.', 'एक व्यक्तीची मालकी; स्वतंत्र केंद्रीय स्थापना प्रमाणपत्र नसते. स्थानिक व कर नोंदणी व्यवसायानुसार लागू होते.', 'एक व्यक्ति का व्यवसाय; अलग केंद्रीय स्थापना प्रमाणपत्र नहीं होता। स्थानीय और कर पंजीकरण गतिविधि पर निर्भर हैं।'), documents: [copy('Owner PAN, identity/address proof, business address proof', 'मालकाचा पॅन, ओळख/पत्ता व व्यवसाय पत्त्याचा पुरावा', 'मालिक का पैन, पहचान/पता और व्यवसाय पते का प्रमाण')], authority: 'Income Tax Department / relevant local authority', complexity: 0.12, tags: ['all', 'trading', 'service'], officialUrl: 'https://www.incometax.gov.in/' },
  { id: 'partnership', group: 'entity', name: copy('Partnership firm', 'भागीदारी संस्था', 'साझेदारी फर्म'), summary: copy('Two or more partners operate under a partnership deed; registration with the Registrar of Firms is available under state law.', 'दोन किंवा अधिक भागीदार भागीदारी करारानुसार व्यवसाय करतात; राज्य कायद्यानुसार फर्म निबंधकाकडे नोंदणी करता येते.', 'दो या अधिक साझेदार साझेदारी विलेख के तहत व्यवसाय करते हैं; राज्य कानून के तहत फर्म रजिस्ट्रार में पंजीकरण किया जा सकता है।'), documents: [copy('Partnership deed, partner PAN/identity proofs, registered office proof', 'भागीदारी करार, भागीदारांचे पॅन/ओळख व नोंदणीकृत कार्यालयाचा पुरावा', 'साझेदारी विलेख, साझेदार पैन/पहचान और पंजीकृत कार्यालय प्रमाण')], authority: 'Maharashtra Registrar of Firms', complexity: 0.28, tags: ['all'], officialUrl: 'https://rof.maharashtra.gov.in/' },
  { id: 'llp', group: 'entity', name: copy('Limited Liability Partnership (LLP)', 'मर्यादित दायित्व भागीदारी (LLP)', 'सीमित दायित्व भागीदारी (LLP)'), summary: copy('A body corporate with separate legal identity and limited liability, incorporated through the Ministry of Corporate Affairs.', 'स्वतंत्र कायदेशीर ओळख व मर्यादित दायित्व असलेली संस्था; कॉर्पोरेट व्यवहार मंत्रालयामार्फत स्थापना.', 'अलग कानूनी पहचान और सीमित दायित्व वाली संस्था; कॉर्पोरेट कार्य मंत्रालय के माध्यम से स्थापना।'), documents: [copy('DPIN/DIN, DSC, partner PAN/identity proof, registered office proof, LLP agreement', 'DPIN/DIN, DSC, भागीदारांचे पॅन/ओळख, कार्यालयाचा पुरावा, LLP करार', 'DPIN/DIN, DSC, साझेदार पैन/पहचान, कार्यालय प्रमाण, LLP समझौता')], authority: 'Ministry of Corporate Affairs (MCA)', complexity: 0.52, tags: ['all'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'opc', group: 'entity', name: copy('One Person Company (OPC)', 'एक व्यक्ती कंपनी (OPC)', 'एक व्यक्ति कंपनी (OPC)'), summary: copy('A company form for a single member, subject to Companies Act eligibility and nominee requirements.', 'एक सदस्यासाठी कंपनीचा प्रकार; कंपनी कायद्यातील पात्रता व नामनिर्देशित व्यक्तीच्या अटी लागू.', 'एक सदस्य के लिए कंपनी का प्रकार; कंपनी अधिनियम की पात्रता और नामांकित व्यक्ति की शर्तें लागू।'), documents: [copy('Member and nominee identity/PAN, DSC/DIN, registered office proof, consent', 'सदस्य व नामनिर्देशित व्यक्तीचे पॅन/ओळख, DSC/DIN, कार्यालयाचा पुरावा व संमती', 'सदस्य और नामांकित व्यक्ति का पैन/पहचान, DSC/DIN, कार्यालय प्रमाण और सहमति')], authority: 'MCA', complexity: 0.58, tags: ['all', 'startup'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'private-limited', group: 'entity', name: copy('Private Limited Company', 'खाजगी मर्यादित कंपनी', 'प्राइवेट लिमिटेड कंपनी'), summary: copy('A separate legal entity with limited liability; incorporation and ongoing filings are governed by the Companies Act.', 'मर्यादित दायित्व असलेली स्वतंत्र कायदेशीर संस्था; स्थापना व पुढील नोंदी कंपनी कायद्यानुसार.', 'सीमित दायित्व वाली अलग कानूनी संस्था; स्थापना और नियमित फाइलिंग कंपनी अधिनियम के अधीन।'), documents: [copy('Director/subscriber PAN and identity, DSC/DIN, name approval, registered office proof, MOA/AOA', 'संचालक/सभासदांचे पॅन व ओळख, DSC/DIN, नाव मंजुरी, कार्यालयाचा पुरावा, MOA/AOA', 'निदेशक/सदस्य पैन और पहचान, DSC/DIN, नाम स्वीकृति, कार्यालय प्रमाण, MOA/AOA')], authority: 'MCA', complexity: 0.68, tags: ['all', 'startup', 'investment'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'public-limited', group: 'entity', name: copy('Public Limited Company', 'सार्वजनिक मर्यादित कंपनी', 'पब्लिक लिमिटेड कंपनी'), summary: copy('A company permitted to offer securities to the public subject to company and securities law requirements.', 'कंपनी व प्रतिभूती कायद्यांच्या अटींनुसार सार्वजनिक गुंतवणूकदारांना प्रतिभूती देऊ शकणारी कंपनी.', 'कंपनी और प्रतिभूति कानून की शर्तों के तहत जनता को प्रतिभूतियां जारी करने वाली कंपनी।'), documents: [copy('Director/subscriber KYC, DSC/DIN, registered office proof, MOA/AOA, capital details', 'संचालक/सभासद KYC, DSC/DIN, कार्यालयाचा पुरावा, MOA/AOA, भांडवल तपशील', 'निदेशक/सदस्य KYC, DSC/DIN, कार्यालय प्रमाण, MOA/AOA, पूंजी विवरण')], authority: 'MCA', complexity: 0.92, tags: ['all', 'investment'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'section-8', group: 'entity', name: copy('Section 8 Company (non-profit)', 'कलम 8 कंपनी (ना-नफा)', 'धारा 8 कंपनी (गैर-लाभकारी)'), summary: copy('A non-profit company for specified charitable objectives; licence and ongoing reporting requirements apply.', 'निर्दिष्ट धर्मादाय उद्दिष्टांसाठी ना-नफा कंपनी; परवाना व नियमित अहवाल आवश्यक.', 'निर्दिष्ट परोपकारी उद्देशों के लिए गैर-लाभकारी कंपनी; लाइसेंस और नियमित रिपोर्टिंग लागू।'), documents: [copy('MOA/AOA, proposed activities, director KYC, registered office proof, declarations', 'MOA/AOA, प्रस्तावित उपक्रम, संचालक KYC, कार्यालयाचा पुरावा, घोषणापत्रे', 'MOA/AOA, प्रस्तावित गतिविधियां, निदेशक KYC, कार्यालय प्रमाण, घोषणाएं')], authority: 'MCA', complexity: 0.78, tags: ['nonprofit'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'producer-company', group: 'entity', name: copy('Producer Company', 'उत्पादक कंपनी', 'प्रोड्यूसर कंपनी'), summary: copy('A company form for eligible primary producers, incorporated and governed under company law.', 'पात्र प्राथमिक उत्पादकांसाठी कंपनीचा प्रकार; कंपनी कायद्यानुसार स्थापना व नियमन.', 'पात्र प्राथमिक उत्पादकों के लिए कंपनी का प्रकार; कंपनी कानून के तहत स्थापना और संचालन।'), documents: [copy('Producer member details, objects, director KYC, registered office proof, MOA/AOA', 'उत्पादक सदस्य तपशील, उद्दिष्टे, संचालक KYC, कार्यालयाचा पुरावा, MOA/AOA', 'उत्पादक सदस्य विवरण, उद्देश्य, निदेशक KYC, कार्यालय प्रमाण, MOA/AOA')], authority: 'MCA', complexity: 0.76, tags: ['agriculture'], officialUrl: 'https://www.mca.gov.in/content/mca/global/en/home.html' },
  { id: 'cooperative', group: 'entity', name: copy('Co-operative Society', 'सहकारी संस्था', 'सहकारी समिति'), summary: copy('Member-owned organization registered under the applicable Maharashtra co-operative law.', 'महाराष्ट्रातील लागू सहकारी कायद्यानुसार नोंदणीकृत सदस्य-मालकीची संस्था.', 'महाराष्ट्र के लागू सहकारी कानून के तहत पंजीकृत सदस्य-स्वामित्व वाली संस्था।'), documents: [copy('By-laws, member list, promoter resolutions, office proof, activity plan', 'उपविधी, सदस्य यादी, प्रवर्तक ठराव, कार्यालयाचा पुरावा, उपक्रम योजना', 'उपविधि, सदस्य सूची, प्रवर्तक प्रस्ताव, कार्यालय प्रमाण, गतिविधि योजना')], authority: 'Maharashtra Co-operation Department', complexity: 0.82, tags: ['cooperative'], officialUrl: 'https://sahakarayukta.maharashtra.gov.in/' },
  { id: 'society-trust', group: 'entity', name: copy('Society or Public Trust', 'संस्था किंवा सार्वजनिक न्यास', 'सोसायटी या सार्वजनिक ट्रस्ट'), summary: copy('Non-profit organizational forms; the proper route depends on purpose, governance, and applicable state law.', 'ना-नफा संस्था प्रकार; उद्देश, प्रशासन व राज्य कायद्यानुसार योग्य मार्ग ठरतो.', 'गैर-लाभकारी संगठन रूप; उद्देश्य, शासन और राज्य कानून के अनुसार उपयुक्त प्रक्रिया चुनें।'), documents: [copy('Memorandum/by-laws or trust deed, governing body details, address proof', 'नियमावली किंवा न्यासपत्र, प्रशासकीय मंडळ तपशील, पत्ता पुरावा', 'नियमावली या ट्रस्ट विलेख, शासी निकाय विवरण, पता प्रमाण')], authority: 'Maharashtra Charity Commissioner / Registrar of Societies', complexity: 0.72, tags: ['nonprofit'], officialUrl: 'https://charity.maharashtra.gov.in/' },
  { id: 'udyam', group: 'general', name: copy('Udyam (MSME) Registration', 'उद्यम (MSME) नोंदणी', 'उद्यम (MSME) पंजीकरण'), summary: copy('MSME classification registration on the official portal; classification criteria and portal rules can change.', 'अधिकृत पोर्टलवरील MSME वर्गीकरण नोंदणी; निकष व पोर्टल नियम बदलू शकतात.', 'आधिकारिक पोर्टल पर MSME वर्गीकरण पंजीकरण; मानदंड और पोर्टल नियम बदल सकते हैं।'), documents: [copy('Aadhaar-linked owner details, PAN, GSTIN where applicable', 'आधार-संबंधित मालक तपशील, पॅन, लागू असल्यास GSTIN', 'आधार-संबद्ध मालिक विवरण, लागू होने पर पैन और GSTIN')], authority: 'Ministry of MSME', complexity: 0.22, tags: ['all', 'msme'], officialUrl: 'https://udyamregistration.gov.in/' },
  { id: 'gst', group: 'general', name: copy('GST Registration', 'GST नोंदणी', 'GST पंजीकरण'), summary: copy('Tax registration when turnover, interstate supply, e-commerce, or other statutory conditions make it applicable.', 'उलाढाल, आंतरराज्य पुरवठा, ई-कॉमर्स किंवा इतर कायदेशीर अटी लागू असल्यास कर नोंदणी.', 'टर्नओवर, अंतरराज्य आपूर्ति, ई-कॉमर्स या अन्य कानूनी शर्तें लागू होने पर कर पंजीकरण।'), documents: [copy('PAN, constitution proof, promoter KYC, principal place proof, bank details', 'पॅन, संस्था पुरावा, प्रवर्तक KYC, मुख्य ठिकाणाचा पुरावा, बँक तपशील', 'पैन, संस्था प्रमाण, प्रवर्तक KYC, मुख्य स्थान प्रमाण, बैंक विवरण')], authority: 'GST Portal', complexity: 0.38, tags: ['all'], officialUrl: 'https://www.gst.gov.in/' },
  { id: 'startup-recognition', group: 'general', name: copy('DPIIT Startup Recognition', 'DPIIT स्टार्टअप मान्यता', 'DPIIT स्टार्टअप मान्यता'), summary: copy('Optional recognition for entities that meet the current Startup India eligibility conditions.', 'सध्याच्या Startup India पात्रता अटी पूर्ण करणाऱ्या संस्थांसाठी ऐच्छिक मान्यता.', 'वर्तमान Startup India पात्रता शर्तें पूरी करने वाली संस्थाओं के लिए वैकल्पिक मान्यता।'), documents: [copy('Incorporation/registration certificate, business description, innovation evidence', 'स्थापना/नोंदणी प्रमाणपत्र, व्यवसाय वर्णन, नवोपक्रम पुरावा', 'स्थापना/पंजीकरण प्रमाणपत्र, व्यवसाय विवरण, नवाचार प्रमाण')], authority: 'DPIIT / Startup India', complexity: 0.4, tags: ['startup'], officialUrl: 'https://www.startupindia.gov.in/' },
  { id: 'shops-establishment', group: 'general', name: copy('Shops and Establishments', 'दुकाने व आस्थापना', 'दुकान एवं प्रतिष्ठान'), summary: copy('State/municipal establishment compliance; applicability and filing depend on the workplace and workforce.', 'राज्य/पालिका आस्थापना अनुपालन; लागूत्व कामाचे ठिकाण व कर्मचाऱ्यांवर अवलंबून.', 'राज्य/नगरपालिका प्रतिष्ठान अनुपालन; लागू होना कार्यस्थल और कर्मचारियों पर निर्भर है।'), documents: [copy('Occupancy/address proof, employer identity, employee details', 'वापर/पत्ता पुरावा, नियोक्ता ओळख, कर्मचारी तपशील', 'कब्जा/पता प्रमाण, नियोक्ता पहचान, कर्मचारी विवरण')], authority: 'Maharashtra Labour Department / local authority', complexity: 0.3, tags: ['service', 'trading', 'office'], officialUrl: 'https://mahakamgar.maharashtra.gov.in/' },
  { id: 'professional-tax', group: 'general', name: copy('Professional Tax (PTEC/PTRC)', 'व्यवसाय कर (PTEC/PTRC)', 'व्यवसाय कर (PTEC/PTRC)'), summary: copy('Maharashtra enrolment/registration obligations depend on entity and employment circumstances.', 'महाराष्ट्र नोंदणी/कर कपात जबाबदाऱ्या संस्था व रोजगार परिस्थितीनुसार लागू होतात.', 'महाराष्ट्र नामांकन/कर कटौती दायित्व इकाई और रोजगार स्थिति पर निर्भर हैं।'), documents: [copy('PAN, constitution proof, address, employer/employee details as applicable', 'पॅन, संस्था व पत्ता पुरावा, लागू असल्यास नियोक्ता/कर्मचारी तपशील', 'पैन, संस्था और पता प्रमाण, लागू होने पर नियोक्ता/कर्मचारी विवरण')], authority: 'Maharashtra GST Department', complexity: 0.28, tags: ['all'], officialUrl: 'https://www.mahagst.gov.in/' },
  { id: 'iec', group: 'general', name: copy('Importer Exporter Code (IEC)', 'आयात-निर्यात कोड (IEC)', 'आयात-निर्यात कोड (IEC)'), summary: copy('DGFT registration generally required for import/export activity, subject to current exemptions.', 'आयात/निर्यात क्रियेसाठी सामान्यतः आवश्यक DGFT नोंदणी; सध्याच्या सूट तपासा.', 'आयात/निर्यात गतिविधि के लिए सामान्यतः आवश्यक DGFT पंजीकरण; वर्तमान छूट जांचें।'), documents: [copy('PAN, bank proof, address proof, entity details', 'पॅन, बँक पुरावा, पत्ता पुरावा, संस्था तपशील', 'पैन, बैंक प्रमाण, पता प्रमाण, संस्था विवरण')], authority: 'Directorate General of Foreign Trade (DGFT)', complexity: 0.34, tags: ['export', 'import'], officialUrl: 'https://www.dgft.gov.in/' },
  { id: 'fssai', group: 'sector', name: copy('FSSAI Food Business Licence/Registration', 'FSSAI अन्न व्यवसाय परवाना/नोंदणी', 'FSSAI खाद्य व्यवसाय लाइसेंस/पंजीकरण'), summary: copy('Food-safety registration/licence category depends on business activity, scale, and current FSSAI rules.', 'अन्न सुरक्षा नोंदणी/परवाना प्रकार क्रिया, आकार व FSSAI नियमांनुसार ठरतो.', 'खाद्य सुरक्षा पंजीकरण/लाइसेंस श्रेणी गतिविधि, स्तर और FSSAI नियमों पर निर्भर है।'), documents: [copy('Premises proof, identity, food category, layout/process details where required', 'जागेचा पुरावा, ओळख, अन्न प्रकार, आवश्यकतेनुसार आराखडा/प्रक्रिया तपशील', 'परिसर प्रमाण, पहचान, खाद्य श्रेणी, आवश्यक होने पर लेआउट/प्रक्रिया विवरण')], authority: 'Food Safety and Standards Authority of India', complexity: 0.56, tags: ['food'], officialUrl: 'https://foscos.fssai.gov.in/' },
  { id: 'factory', group: 'sector', name: copy('Factory plan approval and licence', 'कारखाना आराखडा मंजुरी व परवाना', 'कारखाना मानचित्र स्वीकृति और लाइसेंस'), summary: copy('Factory law applicability and licensing depend on premises, process, power use, and worker thresholds.', 'कारखाना कायदा व परवाना जागा, प्रक्रिया, वीज वापर व कामगार मर्यादांवर अवलंबून.', 'कारखाना कानून और लाइसेंस परिसर, प्रक्रिया, बिजली उपयोग और कर्मचारी सीमा पर निर्भर हैं।'), documents: [copy('Building/layout plans, process and machinery details, safety arrangements, workforce', 'इमारत/आराखडा, प्रक्रिया व यंत्रसामग्री, सुरक्षा व्यवस्था, मनुष्यबळ', 'भवन/लेआउट, प्रक्रिया और मशीनरी विवरण, सुरक्षा व्यवस्था, कार्यबल')], authority: 'Directorate of Industrial Safety and Health (DISH), Maharashtra', complexity: 0.74, tags: ['manufacturing', 'workers'], officialUrl: 'https://mahadish.in/' },
  { id: 'mpcb-consent', group: 'sector', name: copy('MPCB Consent to Establish / Operate', 'MPCB स्थापना / संचालन संमती', 'MPCB स्थापना / संचालन सहमति'), summary: copy('Pollution-control consent may apply depending on industry category, processes, emissions, and current rules.', 'उद्योग वर्ग, प्रक्रिया, उत्सर्जन व नियमांनुसार प्रदूषण नियंत्रण संमती लागू होऊ शकते.', 'उद्योग श्रेणी, प्रक्रिया, उत्सर्जन और नियमों के आधार पर प्रदूषण नियंत्रण सहमति लागू हो सकती है।'), documents: [copy('Project report, site plan, water/air balance, pollution-control proposal', 'प्रकल्प अहवाल, जागेचा आराखडा, पाणी/हवा ताळेबंद, प्रदूषण नियंत्रण प्रस्ताव', 'परियोजना रिपोर्ट, स्थल योजना, जल/वायु संतुलन, प्रदूषण नियंत्रण प्रस्ताव')], authority: 'Maharashtra Pollution Control Board (MPCB)', complexity: 0.84, tags: ['manufacturing', 'pollution', 'hazardous'], officialUrl: 'https://www.mpcb.gov.in/' },
  { id: 'trade-licence', group: 'sector', name: copy('Municipal Trade Licence', 'पालिका व्यापार परवाना', 'नगरपालिका व्यापार लाइसेंस'), summary: copy('Local trade permissions vary by municipal corporation, council, or gram panchayat and business activity.', 'पालिका, नगर परिषद किंवा ग्रामपंचायत व व्यवसायानुसार स्थानिक परवानगी बदलते.', 'नगर निगम, परिषद या ग्राम पंचायत और गतिविधि के अनुसार स्थानीय अनुमति बदलती है।'), documents: [copy('Premises proof, owner identity, activity details, NOC if applicable', 'जागेचा पुरावा, मालक ओळख, व्यवसाय तपशील, लागू असल्यास NOC', 'परिसर प्रमाण, मालिक पहचान, गतिविधि विवरण, लागू होने पर NOC')], authority: 'Relevant local self-government body', complexity: 0.34, tags: ['trading', 'service'], officialUrl: 'https://mahadma.maharashtra.gov.in/' },
  { id: 'epfo', group: 'sector', name: copy('EPFO Establishment Registration', 'EPFO आस्थापना नोंदणी', 'EPFO प्रतिष्ठान पंजीकरण'), summary: copy('Employer registration and coverage depend on establishment type, employee count, and applicable EPF law.', 'नियोक्ता नोंदणी व व्याप्ती आस्थापना प्रकार, कर्मचारी संख्या व EPF कायद्यानुसार.', 'नियोक्ता पंजीकरण और कवरेज प्रतिष्ठान प्रकार, कर्मचारी संख्या और EPF कानून पर निर्भर हैं।'), documents: [copy('Entity PAN, address proof, authorised signatory, employee/payroll details', 'संस्था पॅन, पत्ता पुरावा, अधिकृत स्वाक्षरीकर्ता, कर्मचारी/वेतन तपशील', 'संस्था पैन, पता प्रमाण, अधिकृत हस्ताक्षरकर्ता, कर्मचारी/पेरोल विवरण')], authority: 'Employees Provident Fund Organisation', complexity: 0.42, tags: ['workers'], officialUrl: 'https://www.epfindia.gov.in/' },
  { id: 'esic', group: 'sector', name: copy('ESIC Employer Registration', 'ESIC नियोक्ता नोंदणी', 'ESIC नियोक्ता पंजीकरण'), summary: copy('Coverage depends on establishment location, employee count, wages, and current ESIC notifications.', 'व्याप्ती ठिकाण, कर्मचारी संख्या, वेतन व ESIC अधिसूचनांवर अवलंबून.', 'कवरेज स्थान, कर्मचारियों की संख्या, वेतन और ESIC अधिसूचनाओं पर निर्भर है।'), documents: [copy('Entity details, address, authorised signatory, employee/payroll information', 'संस्था तपशील, पत्ता, अधिकृत स्वाक्षरीकर्ता, कर्मचारी/वेतन माहिती', 'संस्था विवरण, पता, अधिकृत हस्ताक्षरकर्ता, कर्मचारी/पेरोल जानकारी')], authority: 'Employees State Insurance Corporation', complexity: 0.4, tags: ['workers'], officialUrl: 'https://www.esic.gov.in/' },
  { id: 'trademark', group: 'general', name: copy('Trade mark registration', 'व्यापारचिन्ह नोंदणी', 'ट्रेडमार्क पंजीकरण'), summary: copy('Optional intellectual-property protection; search and select the correct class before applying.', 'ऐच्छिक बौद्धिक संपदा संरक्षण; अर्जापूर्वी शोध व योग्य वर्ग निवडा.', 'वैकल्पिक बौद्धिक संपदा संरक्षण; आवेदन से पहले खोज और सही वर्ग चुनें।'), documents: [copy('Applicant details, mark/device representation, goods/services class, use claim proof', 'अर्जदार तपशील, चिन्ह प्रतिमा, वस्तू/सेवा वर्ग, वापर दावा पुरावा', 'आवेदक विवरण, चिह्न चित्र, वस्तु/सेवा वर्ग, उपयोग दावे का प्रमाण')], authority: 'Office of the Controller General of Patents, Designs & Trade Marks', complexity: 0.5, tags: ['all'], officialUrl: 'https://ipindia.gov.in/' },
];

export type TimelineFeatures = { registrations: number; complexity: number; sectorRisk: number; documentsReady: number; identityVerified: boolean };
export type TimelineEstimate = { minimumDays: number; likelyDays: number; maximumDays: number; confidence: 'low' | 'medium'; model: string; trainingNotice: string };

const syntheticTrainingRows: Array<TimelineFeatures & { days: number }> = [
  { registrations: 2, complexity: .15, sectorRisk: 0, documentsReady: 1, identityVerified: true, days: 5 },
  { registrations: 3, complexity: .25, sectorRisk: 0, documentsReady: .8, identityVerified: true, days: 9 },
  { registrations: 4, complexity: .4, sectorRisk: .2, documentsReady: .8, identityVerified: true, days: 13 },
  { registrations: 5, complexity: .5, sectorRisk: .2, documentsReady: .6, identityVerified: true, days: 19 },
  { registrations: 6, complexity: .65, sectorRisk: .4, documentsReady: .8, identityVerified: true, days: 23 },
  { registrations: 7, complexity: .75, sectorRisk: .7, documentsReady: .6, identityVerified: true, days: 34 },
  { registrations: 8, complexity: .9, sectorRisk: 1, documentsReady: .4, identityVerified: false, days: 49 },
  { registrations: 4, complexity: .3, sectorRisk: 0, documentsReady: .4, identityVerified: false, days: 21 },
  { registrations: 5, complexity: .45, sectorRisk: .6, documentsReady: 1, identityVerified: true, days: 17 },
  { registrations: 9, complexity: .85, sectorRisk: .8, documentsReady: .9, identityVerified: true, days: 31 },
  { registrations: 3, complexity: .2, sectorRisk: .1, documentsReady: .9, identityVerified: false, days: 14 },
  { registrations: 6, complexity: .55, sectorRisk: .5, documentsReady: .3, identityVerified: false, days: 38 },
];

export function estimateRegistrationTimeline(features: TimelineFeatures): TimelineEstimate {
  const distance = (row: TimelineFeatures, input: TimelineFeatures) => Math.sqrt(
    ((row.registrations - input.registrations) / 8) ** 2
    + (row.complexity - input.complexity) ** 2
    + (row.sectorRisk - input.sectorRisk) ** 2
    + (row.documentsReady - input.documentsReady) ** 2
    + (Number(row.identityVerified) - Number(input.identityVerified)) ** 2,
  );
  const neighbors = syntheticTrainingRows.map((row) => ({ row, distance: distance(row, features) })).sort((a, b) => a.distance - b.distance).slice(0, 5);
  const weights = neighbors.map(({ distance: gap }) => 1 / (gap + .08));
  const weightTotal = weights.reduce((sum, weight) => sum + weight, 0);
  const likelyDays = Math.max(1, Math.round(neighbors.reduce((sum, item, index) => sum + item.row.days * weights[index], 0) / weightTotal));
  const variance = Math.sqrt(neighbors.reduce((sum, item, index) => sum + weights[index] * (item.row.days - likelyDays) ** 2, 0) / weightTotal);
  const spread = Math.max(3, Math.ceil(variance * 1.35));
  return {
    minimumDays: Math.max(1, likelyDays - spread),
    likelyDays,
    maximumDays: likelyDays + spread,
    confidence: neighbors[0].distance < .18 && variance < 8 ? 'medium' : 'low',
    model: 'K-nearest-neighbour prototype estimator',
    trainingNotice: 'Calibrated only on synthetic demonstration scenarios. Not an official SLA or a production-trained model.',
  };
}